### ISSUE TITLE
HTTP-Status codes other than 200 interferes with WAF

### ISSUE THREAD

**Issue by tomkerb** [SCS-CBU-CED-IAM/mobileid-helper#82]
The helper application transmits MobileID SIM-Card state information via HTTP-Status codes to the webbrowser. This behaviour, inteferes with a possible WAF between helper application and the webbrowser, which intercepts any HTTP-Status other than 200. I suggest to implement the whole application logic into the helper application.

**Comment by phaupt** [comment]
Thank you for pointing out this issue. I agree with you, the HTTP status code of the helper appliaction should be 200/OK. The status code has been use to define the error/warning category (yellow or red button) but instead a dedicated new header entry should be used for that. Will be fixed with the next commit.

**Comment by phaupt** [comment]
A "user cancel" will now lead to the following response in the helper application:

```
HTTP/1.1 200 OK
Date: Tue, 14 Mar 2017 08:23:25 GMT
Server: Apache/2.4.18 (Ubuntu)
MID-Class: 901
Vary: Accept-Encoding
Content-Length: 260
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=utf-8

<p>The selected Mobile ID is not ready for use.</p><p><strong>Problem:</strong> The request has been canceled by the user.</p><p><strong>Solution hint:</strong> To complete the request it has to be accepted and confirmed with the Mobile ID PIN by the user.</p>
```
